In [1]:
import pandas as pd
import numpy as np

In [3]:
chunksize = 10 ** 5

In [5]:
train_df = pd.DataFrame()

In [7]:
for chunk in pd.read_csv("/Users/prathikraju/Downloads/train_data.csv", chunksize = chunksize):
    train_df = pd.concat([train_df, chunk])

In [11]:
train_df.shape

(5531451, 190)

In [19]:
train_df.isna().sum()*100/len(train_df)

customer_ID     0.000000
S_2             0.000000
P_2             0.831337
D_39            0.000000
B_1             0.000000
                 ...
D_141           1.835829
D_142          82.926577
D_143           1.835829
D_144           0.736281
D_145           1.835829
Length: 190, dtype: float64

In [21]:
train_df.head(10)

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-03-09,0.938469,0.001733,0.008724,1.006838,0.009228,0.124035,0.008771,0.004709,...,NaN,NaN,NaN,0.002427,0.003706,0.003818,NaN,0.000569,0.000610,0.002674
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-04-07,0.936665,0.005775,0.004923,1.000653,0.006151,0.126750,0.000798,0.002714,...,NaN,NaN,NaN,0.003954,0.003167,0.005032,NaN,0.009576,0.005492,0.009217
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-05-28,0.954180,0.091505,0.021655,1.009672,0.006815,0.123977,0.007598,0.009423,...,NaN,NaN,NaN,0.003269,0.007329,0.000427,NaN,0.003429,0.006986,0.002603
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-06-13,0.960384,0.002455,0.013683,1.002700,0.001373,0.117169,0.000685,0.005531,...,NaN,NaN,NaN,0.006117,0.004516,0.003200,NaN,0.008419,0.006527,0.009600
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-07-16,0.947248,0.002483,0.015193,1.000727,0.007605,0.117325,0.004653,0.009312,...,NaN,NaN,NaN,0.003671,0.004946,0.008889,NaN,0.001670,0.008126,0.009827
5,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-08-04,0.945964,0.001746,0.007863,1.005006,0.004220,0.110946,0.009857,0.009866,...,NaN,NaN,NaN,0.001924,0.008598,0.004529,NaN,0.000674,0.002223,0.002884
6,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-09-18,0.940705,0.002183,0.018859,1.008024,0.004509,0.103329,0.006603,0.000783,...,NaN,NaN,NaN,0.001336,0.004361,0.009387,NaN,0.007727,0.007661,0.002225
7,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-10-08,0.914767,0.003029,0.014324,1.000242,0.000263,0.108115,0.009527,0.007836,...,NaN,NaN,NaN,0.002397,0.008452,0.005553,NaN,0.001831,0.009616,0.007385
8,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-11-20,0.950845,0.009896,0.016888,1.003995,0.001789,0.102792,0.002519,0.009817,...,NaN,NaN,NaN,0.009742,0.003968,0.007945,NaN,0.008722,0.004369,0.000995
9,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-12-04,0.868580,0.001082,0.001930,1.007504,0.001772,0.100470,0.004626,0.006073,...,NaN,NaN,NaN,0.003611,0.009607,0.007266,NaN,0.008763,0.004753,0.009068

In [23]:
train_label = pd.read_csv("/Users/prathikraju/Downloads/train_labels.csv")

In [27]:
train_label.shape

(458913, 2)

In [33]:
train_lables = train_label.sample(frac = 0.2, random_state = 42)

In [35]:
del train_label

In [37]:
train_labels = train_lables

In [39]:
del train_lables

In [41]:
train_labels.shape

(91783, 2)

In [43]:
train_labels.head(5)

                                              customer_ID  target
33412   12c761e40348fa242de0356426fa9547f0feea34d1f57b...       0
350485  c34b0cf3175108892e42e9382e8177847ac15636870604...       1
36829   14aff3c0e0ed2aaaef6deb127f2541b67fdd0002615bfd...       0
444951  f82be644eb90ab65d737b6dfc5de670559fa2ca23c98ea...       0
17537   09dec6d53f0f12db6edcaecbb4d2bddf41f220ba9569d1...       0

In [47]:
train_labels = train_labels.set_index('customer_ID')

In [49]:
train_df = train_df.set_index('customer_ID')

In [51]:
train_m = pd.merge(train_labels, train_df, how = 'inner', on = 'customer_ID')

In [53]:
train_m.shape

(1107082, 190)

In [55]:
train_m.head(5)

,target,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
customer_ID,,,,,,,,,,,,,,,,,,,,,
12c761e40348fa242de0356426fa9547f0feea34d1f57bf4de9c50e7b236c300,0,2017-03-21,0.628534,0.004250,0.017667,0.815468,0.005736,0.265531,0.005933,0.015981,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12c761e40348fa242de0356426fa9547f0feea34d1f57bf4de9c50e7b236c300,0,2017-04-21,0.669914,0.418321,0.354284,1.000587,0.009774,0.176196,0.007370,0.005623,...,NaN,NaN,NaN,0.003869,0.008332,0.005805,NaN,0.006603,0.007874,0.002185
12c761e40348fa242de0356426fa9547f0feea34d1f57bf4de9c50e7b236c300,0,2017-05-08,0.661933,0.003989,0.244867,1.008683,0.005743,0.169471,0.005953,0.004846,...,NaN,NaN,NaN,0.004872,0.008471,0.006763,NaN,0.009782,0.007285,0.000121
12c761e40348fa242de0356426fa9547f0feea34d1f57bf4de9c50e7b236c300,0,2017-06-14,0.644270,0.009351,0.017799,0.668398,0.003148,0.174020,0.006656,0.013463,...,NaN,NaN,NaN,0.009246,0.009905,0.008673,NaN,0.003927,0.001159,0.000433
12c761e40348fa242de0356426fa9547f0feea34d1f57bf4de9c50e7b236c300,0,2017-07-26,0.688055,0.002832,0.009458,0.779692,0.000870,0.174547,0.009100,0.011599,...,NaN,NaN,NaN,0.004311,0.006488,0.004953,NaN,0.009283,0.003769,0.006124

In [ ]:
train_m.to_csv("sample_data.csv", index = False)

In [63]:
train_m.dtypes.value_counts()

float64    185
object       3
int64        2
Name: count, dtype: int64

In [65]:
train_m.select_dtypes(include = 'object').columns.tolist()

['S_2', 'D_63', 'D_64']

In [67]:
train_m.select_dtypes(include = 'int64').columns.tolist()

['target', 'B_31']

In [71]:
train_m['target'].value_counts()

target
0    834188
1    272894
Name: count, dtype: int64

In [77]:
train_m['target'].value_counts(normalize=True)

target
0    0.753502
1    0.246498
Name: proportion, dtype: float64

In [91]:
train_m.isna().mean().sort_values(ascending = False).head(20)

D_87     0.999265
D_88     0.998940
D_108    0.994888
D_111    0.993995
D_110    0.993995
B_39     0.993608
D_73     0.989545
B_42     0.986819
D_134    0.966734
D_138    0.966734
D_135    0.966734
D_136    0.966734
D_137    0.966734
R_9      0.943945
B_29     0.930888
D_106    0.903368
D_132    0.903144
D_49     0.902609
R_26     0.890855
D_66     0.887946
dtype: float64

In [93]:
all_missing = train_m.isna().mean() ==  1

In [99]:
all_missing[all_missing].index.tolist()

[]

In [107]:
train_m['S_2'].min(), train_m['S_2'].max()

('2017-03-01', '2018-03-31')

In [115]:
train_m.sort_values(['customer_ID', 'S_2']).groupby('customer_ID').tail(1)

,target,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
customer_ID,,,,,,,,,,,,,,,,,,,,,
000098081fde4fd64bc4d503a5d6f86a0aedc425c96f5235f98b0f47c9d7d8d4,0,2018-03-12,0.477116,0.000467,0.009413,1.009217,0.007775,0.267037,0.006128,0.125927,...,NaN,NaN,NaN,0.006010,0.005221,0.000937,NaN,0.009790,0.003703,0.006274
000445609ff2a39d2dd02484899affa5696210a95f6869f26390bd26eeb3b651,0,2018-03-17,0.978897,0.001221,0.006584,0.819623,0.001521,0.177809,0.006464,0.010949,...,NaN,NaN,NaN,0.009010,0.007145,0.005159,NaN,0.000031,0.004060,0.000315
0004837f0c785928a29a6f83f70f4a1c54caec483a773ff4b5b317ac251abda0,0,2018-03-02,0.642295,0.685210,0.429796,0.024450,0.005188,0.221216,0.009708,0.357104,...,NaN,NaN,NaN,0.002107,0.001215,0.003079,NaN,0.003943,0.005832,0.000346
0004ec03ca1ab2adb9aa260c61ba5dce8185e19d3ab704029f989240c733b6d0,0,2018-03-08,0.980221,0.009431,0.028153,1.008633,0.503520,0.130219,0.005540,0.006706,...,NaN,NaN,NaN,0.009336,0.006395,0.000355,NaN,0.001410,0.007432,0.009696
00050d84c6d26e26cd2b18c3eed83d3130c270e2361470ff272f9409103d067f,0,2018-03-22,1.006598,0.119977,0.045083,1.005729,0.007899,0.050511,0.192333,0.007466,...,NaN,NaN,NaN,0.004660,0.001356,0.003087,NaN,0.004812,0.004934,0.007411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fffe2bc02423407e33a607660caeed076d713d8a5ad32321530e92704835da88,1,2018-03-17,0.408619,0.765793,1.150845,0.010803,0.008213,1.169100,0.004637,0.364892,...,NaN,NaN,NaN,0.007866,0.009716,0.005847,NaN,0.009344,0.003953,0.006302
ffff518bb2075e4816ee3fe9f3b152c57fc0e6f01bf7fdd3e5b57cfcbee30286,0,2018-03-22,0.831279,0.033670,0.292360,0.055656,0.006953,NaN,0.005791,0.233078,...,NaN,NaN,NaN,0.004393,0.006185,0.001480,NaN,0.004794,0.009230,0.006435
ffff9984b999fccb2b6127635ed0736dda94e544e67e026eee4d20f680639ff6,0,2018-03-07,0.800522,0.267018,0.020563,1.007023,0.000957,0.066648,0.007424,0.006314,...,NaN,NaN,NaN,0.006035,0.002869,0.002149,NaN,0.008031,0.000340,0.002148
ffffa5c46bc8de74f5a4554e74e239c8dee6b9baf388145b2c3d01967fcce461,1,2018-03-23,0.754129,0.008619,0.015838,0.714486,0.000993,0.408849,0.003392,0.050048,...,NaN,NaN,NaN,1.009894,0.004478,0.949723,0.446255,1.009310,0.002502,0.185527
fffff1d38b785cef84adeace64f8f83db3a0c31e8d92eaba8b115f71cab04681,0,2018-03-14,0.982175,0.002474,0.000077,0.992880,0.000809,0.119165,0.003287,0.014092,...,NaN,NaN,NaN,0.007316,0.002888,0.006207,NaN,0.005110,0.003184,0.001914

In [119]:
months_per_customer = train_m.groupby('customer_ID').size()

In [121]:
months_per_customer.value_counts().sort_values(ascending = False)

13    77348
12     2115
10     1329
9      1278
2      1217
8      1169
11     1159
3      1158
6      1109
7      1046
1       984
4       938
5       933
Name: count, dtype: int64

In [145]:
train_m = train_m.reset_index()

In [147]:
customer_data = train_m.groupby('customer_ID').agg(min_date = ('S_2','min'), max_date =('S_2', 'max'), target = ('target','mean'), observations = ('customer_ID', 'nunique'))

In [149]:
customer_data

,min_date,max_date,target,observations
customer_ID,,,,
000098081fde4fd64bc4d503a5d6f86a0aedc425c96f5235f98b0f47c9d7d8d4,2017-03-11,2018-03-12,0.0,1
000445609ff2a39d2dd02484899affa5696210a95f6869f26390bd26eeb3b651,2017-03-10,2018-03-17,0.0,1
0004837f0c785928a29a6f83f70f4a1c54caec483a773ff4b5b317ac251abda0,2017-03-01,2018-03-02,0.0,1
0004ec03ca1ab2adb9aa260c61ba5dce8185e19d3ab704029f989240c733b6d0,2017-03-09,2018-03-08,0.0,1
00050d84c6d26e26cd2b18c3eed83d3130c270e2361470ff272f9409103d067f,2017-03-14,2018-03-22,0.0,1
...,...,...,...,...
fffe2bc02423407e33a607660caeed076d713d8a5ad32321530e92704835da88,2017-08-30,2018-03-17,1.0,1
ffff518bb2075e4816ee3fe9f3b152c57fc0e6f01bf7fdd3e5b57cfcbee30286,2017-03-22,2018-03-22,0.0,1
ffff9984b999fccb2b6127635ed0736dda94e544e67e026eee4d20f680639ff6,2017-03-16,2018-03-07,0.0,1
ffffa5c46bc8de74f5a4554e74e239c8dee6b9baf388145b2c3d01967fcce461,2017-03-25,2018-03-23,1.0,1
fffff1d38b785cef84adeace64f8f83db3a0c31e8d92eaba8b115f71cab04681,2017-03-20,2018-03-14,0.0,1

In [151]:
customer_data.dtypes

min_date         object
max_date         object
target          float64
observations      int64
dtype: object

In [153]:
customer_data['min_date'] = pd.to_datetime(customer_data['min_date'])
customer_data['max_date'] = pd.to_datetime(customer_data['max_date'])

In [155]:
pip install jupyterlab-git

python(98895) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

Collecting jupyterlab-git
  Downloading jupyterlab_git-0.52.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: jupyter-server<3,>=2.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from jupyterlab-git) (2.14.1)
Collecting nbdime~=4.0.1 (from jupyterlab-git)
  Downloading nbdime-4.0.4-py3-none-any.whl.metadata (9.3 kB)
Requirement already satisfied: nbformat in /opt/anaconda3/lib/python3.12/site-packages (from jupyterlab-git) (5.10.4)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from jupyterlab-git) (24.1)
Requirement already satisfied: pexpect in /opt/anaconda3/lib/python3.12/site-packages (from jupyterlab-git) (4.8.0)
Requirement already satisfied: traitlets~=5.0 in /opt/anaconda3/lib/python3.12/site-packages (from jupyterlab-git) (5.14.3)
Requirement already satisfied: anyio>=3.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (4.2.0)
Requirement already satisfied: argon2-cffi>=21.1 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (21.3.0)
Requirement already satisfied: jinja2>=3.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (3.1.4)
Requirement already satisfied: jupyter-client>=7.4.4 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (5.7.2)
Requirement already satisfied: jupyter-events>=0.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (0.4.4)
Requirement already satisfied: nbconvert>=6.4.4 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (7.16.4)
Requirement already satisfied: overrides>=5.0 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (7.4.0)
Requirement already satisfied: prometheus-client>=0.9 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (0.14.1)
Requirement already satisfied: pyzmq>=24 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (25.1.2)
Requirement already satisfied: send2trash>=1.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (0.17.1)
Requirement already satisfied: tornado>=6.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (6.4.1)
Requirement already satisfied: websocket-client>=1.7 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-server<3,>=2.0.1->jupyterlab-git) (1.8.0)
Requirement already satisfied: colorama in /opt/anaconda3/lib/python3.12/site-packages (from nbdime~=4.0.1->jupyterlab-git) (0.4.6)
Requirement already satisfied: gitpython!=2.1.4,!=2.1.5,!=2.1.6 in /opt/anaconda3/lib/python3.12/site-packages (from nbdime~=4.0.1->jupyterlab-git) (3.1.43)
Requirement already satisfied: pygments in /opt/anaconda3/lib/python3.12/site-packages (from nbdime~=4.0.1->jupyterlab-git) (2.15.1)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from nbdime~=4.0.1->jupyterlab-git) (2.32.3)
Requirement already satisfied: fastjsonschema>=2.15 in /opt/anaconda3/lib/python3.12/site-packages (from nbformat->jupyterlab-git) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in /opt/anaconda3/lib/python3.12/site-packages (from nbformat->jupyterlab-git) (4.23.0)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/lib/python3.12/site-packages (from pexpect->jupyterlab-git) (0.7.0)
Requirement already satisfied: idna>=2.8 in /opt/anaconda3/lib/python3.12/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (3.7)
Requirement already satisfied: sniffio>=1.1 in /opt/anaconda3/lib/python3.12/site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in /opt/anaconda3/lib/python3.12/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.0.1->jupyterlab-git) (21.2.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitpython!=2.1.4,!=2.1.5,!=2.1.6->nbdime~=4.0.1->jupyterlab-git) (4.0.7)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2>=3.0.3->jupyter-server<3,>=2.0.1->jupyterlab-git) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupyterlab-git) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupyterlab-git) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupyterlab-git) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema>=2.6->nbformat->jupyterlab-git) (0.10.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-client>=7.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter-server<3,>=2.0.1->jupyterlab-git) (3.10.0)
Requirement already satisfied: python-json-logger>=2.0.4 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (6.0.1)
Requirement already satisfied: rfc3339-validator in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.1.1)
Requirement already satisfied: beautifulsoup4 in /opt/anaconda3/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (4.1.0)
Requirement already satisfied: defusedxml in /opt/anaconda3/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /opt/anaconda3/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.1.2)
Requirement already satisfied: mistune<4,>=2.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (2.0.4)
Requirement already satisfied: nbclient>=0.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.8.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/anaconda3/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.5.0)
Requirement already satisfied: tinycss2 in /opt/anaconda3/lib/python3.12/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.2.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->nbdime~=4.0.1->jupyterlab-git) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->nbdime~=4.0.1->jupyterlab-git) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests->nbdime~=4.0.1->jupyterlab-git) (2025.1.31)
Requirement already satisfied: six>=1.9.0 in /opt/anaconda3/lib/python3.12/site-packages (from bleach!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.16.0)
Requirement already satisfied: webencodings in /opt/anaconda3/lib/python3.12/site-packages (from bleach!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (0.5.1)
Requirement already satisfied: smmap<5,>=3.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython!=2.1.4,!=2.1.5,!=2.1.6->nbdime~=4.0.1->jupyterlab-git) (4.0.0)
Collecting fqdn (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.0.1->jupyterlab-git)
  Downloading fqdn-1.5.1-py3-none-any.whl.metadata (1.4 kB)
Collecting isoduration (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.0.1->jupyterlab-git)
  Downloading isoduration-20.11.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: jsonpointer>1.13 in /opt/anaconda3/lib/python3.12/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (2.1)
Collecting uri-template (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.0.1->jupyterlab-git)
  Downloading uri_template-1.3.0-py3-none-any.whl.metadata (8.8 kB)
Collecting webcolors>=24.6.0 (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.0.1->jupyterlab-git)
  Downloading webcolors-25.10.0-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: cffi>=1.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.17.1)
Requirement already satisfied: soupsieve>1.2 in /opt/anaconda3/lib/python3.12/site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.0.1->jupyterlab-git) (2.5)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.12/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.0.1->jupyterlab-git) (2.21)
Requirement already satisfied: arrow>=0.15.0 in /opt/anaconda3/lib/python3.12/site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.0.1->jupyterlab-git) (1.2.3)
Downloading jupyterlab_git-0.52.0-py3-none-any.whl (370 kB)
Downloading nbdime-4.0.4-py3-none-any.whl (5.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 13.1 MB/s eta 0:00:00 0:00:01m
Downloading webcolors-25.10.0-py3-none-any.whl (14 kB)
Downloading fqdn-1.5.1-py3-none-any.whl (9.1 kB)
Downloading isoduration-20.11.0-py3-none-any.whl (11 kB)
Downloading uri_template-1.3.0-py3-none-any.whl (11 kB)
Installing collected packages: webcolors, uri-template, fqdn, isoduration, nbdime, jupyterlab-git
Successfully installed fqdn-1.5.1 isoduration-20.11.0 jupyterlab-git-0.52.0 nbdime-4.0.4 uri-template-1.3.0 webcolors-25.10.0
Note: you may need to restart the kernel to use updated packages.